<?php
use App\Enums\ContactActionEnum;
use App\Models\Contact;
?>
<form method="post" action="index.php?action=<?php echo ContactActionEnum::Save->value; ?>">
    <?php if (isset($contact)): ?>
        <input type="hidden" name="id" value="<?php echo $contact->getId(); ?>">
    <?php endif; ?>
    <table class="edit">
        <tbody>
        <tr>
            <td class="first-colunm"><label for="firstname">Vorname:</label></td>
            <td>
                <input type="text" id="firstname" name="firstname" required
                       value="<?php echo old('firstname', $contact ?? null); ?>">
                <?php if(isset($errors['firstname'])): ?>
                    <div class="error"><?php echo htmlspecialchars($errors['firstname']);?></div>
                <?php endif;?>
            </td>

        </tr>
        <tr>
            <td class="first-colunm"><label for="lastname">Nachname:</label></td>
            <td>
                <input type="text" id="lastname" name="lastname" required
                       value="<?php echo old('lastname', $contact ?? null); ?>">
                <?php if(isset($errors['lastname'])): ?>
                <div class="error"><?php echo htmlspecialchars($errors['lastname']);?></div>
                <?php endif;?>
            </td>
        </tr>
        <tr>
            <td class="first-colunm"><label for="email">E-Mail:</label></td>
            <td>
                <input type="email" id="email" name="email" required
                       value="<?php echo old('email', $contact ?? null); ?>">
                <?php if(isset($errors['email'])): ?>
                <div class="error"><?php echo htmlspecialchars($errors['email']);?></div>
                <?php endif;?>
            </td>
        </tr>
        <tr>
            <td class="first-colunm"><label for="title">Jobbeschreibung:</label></td>
            <td>
                <input type="text" id="title" name="title"
                       value="<?php echo old('title', $contact ?? null); ?>">
                <?php if(isset($errors['title'])): ?>
                <div class="error"><?php echo htmlspecialchars($errors['title']);?></div>
                <?php endif;?>
            </td>
        </tr>
        <tr>
            <td class="first-colunm"><label for="skills">Skills:</label></td>
            <td>
                <input type="text" id="skills" name="skills"
                       value="<?php echo old('skills', $contact ?? null); ?>">
                <?php if(isset($errors['skills'])): ?>
                <div class="error"><?php echo htmlspecialchars($errors['skills']);?></div>
                <?php endif;?>
            </td>
        </tr>
        <tr>
            <td class="first-colunm"><label for="about">Über mich:</label></td>
            <td>
                <textarea id="about" name="about"><?php echo old('about', $contact ?? null); ?></textarea>
                <?php if(isset($errors['about'])): ?>
                <div class="error"><?php echo htmlspecialchars($errors['about']);?></div>
                <?php endif;?>
            </td>
        </tr>
        </tbody>
    </table>
    <div class="actions">
        <a href="index.php" class="btn btn-secondary"><i class="fas fa-arrow-left"></i> Abbrechen</a>
        <button type="submit" class="btn btn-primary"><i class="fas fa-save"></i> Speichern</button>
    </div>
</form>

