<?php
    use App\Models\Contact;
global $contacts;
?><!DOCTYPE html>
<html lang="de">
<head>
    <title>Liste von Kontakten</title>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="assets/styles/main.css">
</head>
<body>
    <header>
        <h1>Kontakte</h1>
        <nav>
            <a href="index.php">Home</a>
        </nav>
    </header>
    <main>
        <table >
            <thead>
                <tr>
                    <th>Name</th>
                    <th>E-mail</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($contacts as $contact): ?>
                    <?php /** @var \App\Models\Contact $contact */ ?>
                    <tr>
                        <td><?php echo htmlspecialchars("{$contact ->getFirstname()} {$contact->getLastname()}")?></td>
                        <td><?php echo htmlspecialchars($contact->getEmail())?></td>
                    </tr>
                <?php endforeach;?>
            </tbody>
        </table>
    </main>
    <footer>
        <p>&copy; Max Wild</p>
    </footer>
</body>
</html>